[package]
name = "quill"
version = "0.2.0"
entrypoint = "src/quill.typ"
authors = ["Mc-Zen"]
license = "MIT"
description = "A library for creating quantum circuit diagrams."
homepage = "https://github.com/Mc-Zen/quill"
exclude = [ "/docs/*"]
keywords = ["quantum circuit diagram", "quantikz", "qcircuit"]